[package]
name = "qrt_rust_utils"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11.0"
serde = { version = "1.0.130", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }
#futures = "0.3.14"
tokio = { version = "1.13.0", features = ["full"] }
mongodb = { version = "2.0.1", default-features = false, features = ["async-std-runtime", "bson-chrono-0_4"] }
reqwest = { version = "0.11.6", features = ['socks'] }
tracing = { version = "0.1.29", features = ["log"] }
#tracing-futures = { version = "0.2.5", default-features = false }
tracing-subscriber = { version = "0.3.1", features = ["local-time"] }
tracing-log = "0.1.2"
fruently = { version = "0.10.0", features = [] }
lazy_static = "1.4.0"
serde-enum-str = "0.2.4"
serde_with = { version = "1.11.0", features = ["chrono"] }
tracing-serde = "0.1.2"
qrt_rust_macros = { path = 'qrt_rust_macros', optional = true }
derive_builder = "0.10.2"
async-recursion = "0.3.2"
regex = "1.5.4"
futures = "0.3.17"
thiserror = "1.0.30"
anyhow = "1.0.45"
async-trait = "0.1.51"
macro-attr = "0.2.0"
[dev-dependencies]
qrt_rust_macros = { path = 'qrt_rust_macros' }
[workspace]
members = ["qrt_rust_macros",
]
exclude = []

[features]
derive = ["qrt_rust_macros"]
