[package]
name = "qrt_rust_utils"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }
futures = "0.3.14"
tokio = { version = "1", features = ["full"] }
mongodb = { version = "2.0.0-beta.2", default-features = false, features = ["async-std-runtime"] }
reqwest = { version = "0.11", features = ['socks'] }
tracing = { version = "0.1", features = ["log"] }
tracing-futures = { version = "0.2.5", default-features = false }
tracing-subscriber = { version = "0.2.12" }
tracing-bunyan-formatter = "0.2.4"
tracing-log = "0.1.2"
tracing-test = "0.1.0"
tracing-honeycomb = "0.4.1"
libhoney-rust = "0.1.6"
[workspace]
members = ["qrt_rust_macros"]
exclude = []
[[bin]]
path = "./src/test_honeycomb.rs"
name = "test_honeycomb"