[package]
name = "qrt_rust_utils"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }
futures = "0.3.14"
tokio = { version = "1", features = ["full"] }
mongodb = { version = "2.0.0-beta.2", default-features = false, features = ["async-std-runtime"] }
reqwest = { version = "0.11", features = ['socks'] }

