[package]
name = "tg_notification"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mscheduler = "0"
serde = "1"
serde-enum-str = "0"
